export const fakeTeams = [
  {
    name: "Space Invaders",
    admins: ["Eshita Das", "Sammridhhi Patil"],
    members: ["Shreya Roy", "Riya Das", "Eshita Das", "Sammridhhi Patil"],
    skills: [
      "React.js",
      "Next.js",
      "C",
      "php",
      "mySql",
      "AWS",
      "Figma",
      "Docker",
      "Kubernetes",
      "AI/ML",
    ],
    desc: "lorem ipsum dolor sit. temae ameka dolor dolor lorem ipsum dolor sit.",
    githubLink: "https://github.com/Edasgh",
    email: "edas25564@gmail.com",
  },

  {
    name: "Nervewreckers",
    admins: ["Eshita Das", "Sammridhhi Patil"],
    members: ["Shreya Roy", "Riya Das", "Eshita Das", "Sammridhhi Patil"],
    skills: [
      "React.js",
      "Next.js",
      "C",
      "php",
      "mySql",
      "AWS",
      "Figma",
      "Docker",
      "Kubernetes",
      "AI/ML",
    ],
    desc: "lorem ipsum dolor sit. temae ameka dolor dolor lorem ipsum dolor sit.lorem ipsum dolor sit. temae a",
    githubLink: "https://github.com/Edasgh",
    email: "yteshita2023@gmail.com",
  },
  {
    name: "Test Team",
    admins: ["Eshita Das", "Sammridhhi Patil"],
    members: ["Shreya Roy", "Riya Das", "Eshita Das", "Sammridhhi Patil","Sagnika Goswami","Tanaya Ghosh"],
    skills: ["React.js", "Next.js", "C", "php", "mySql", "AWS", "Figma"],
    desc: "lorem ipsum dolor sit. temae ameka dolor dolor lorem ipsum dolor sit.",
    githubLink: "https://github.com/Edasgh",
    email: "eshitadas704@gmail.com",
  },
];

export const fakeTeamMates = [
  {
    name: "Eshita Das",
    email: "edas25564@gmail.com",
    country: "IN",
    githubID: "Edasgh",
    bio: "lorem ipsum dolor sit. temae ameka dolor dolor lorem ipsum dolor sit.lorem ipsum dolor sit. temae a",
    skills: [
      "React.js",
      "Next.js",
      "C",
      "php",
      "mySql",
      "AWS",
      "Figma",
      "Docker",
      "Kubernetes",
      "AI/ML",
    ],
  },
  {
    name: "Ritu Das",
    email: "ritudass1234@gmail.com",
    country: "IN",
    githubID: "Rdsgh",
    bio: "lorem ipsum dolor sit. temae ameka dolor dolor lorem ipsum dolor sit.",
    skills: [
      "React.js",
      "Next.js",
      "C",
      "php",
      "mySql",
      "AWS",
    ],
  },
  {
    name: "Priyanka Khan",
    email: "khanpriyanka2023@gmail.com",
    country: "US",
    githubID: "Uttalgeria",
    bio: "lorem ipsum dolor sit. temae ameka dolor dolor lorem ipsum dolor sit.",
    skills: [
      "React.js",
      "Next.js",
      "C",
      "php",
      "mySql",
      "AWS",
    ],
  },
];
